### ISSUE TITLE
/freeze is bugged

### ISSUE THREAD

**Issue by shadowolfyt** [TerraMagnum/TerraTools#14]
I did /freeze and I moved and got kicked. Logging back in it kicked me again for 'Invalid move player packet received'

**Comment by shadowolfyt** [comment]
[13:56:54 INFO]: shadowolfyt issued server command: /freeze shadowolfyt
[13:56:54 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'freeze' in plugin TCC v0.0.1-DEV1
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-b605b31-f4822eb]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-b605b31-f4822eb]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650) ~[spigot.jar:git-Spigot-b605b31-f4822eb]
        at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1353) [spigot.jar:git-Spigot-b605b31-f4822eb]
        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1188) [spigot.jar:git-Spigot-b605b31-f4822eb]
        at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-b605b31-f4822eb]
        at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-b605b31-f4822eb]
        at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-b605b31-f4822eb]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_121]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_121]
        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-b605b31-f4822eb]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot.jar:git-Spigot-b605b31-f4822eb]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-b605b31-f4822eb]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-b605b31-f4822eb]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-b605b31-f4822eb]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_11_R1.entity.CraftArrow cannot be cast to org.bukkit.entity.LivingEntity
        at io.github.terramagnum.tutil.setStill(tutil.java:25) ~[?:?]
        at io.github.terramagnum.commands.message(commands.java:94) ~[?:?]
        at io.github.terramagnum.commandcore.onCommand(commandcore.java:48) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-b605b31-f4822eb]
        ... 15 more
[13:56:54 INFO]: shadowolfyt lost connection: Invalid move player packet received
[13:56:54 INFO]: ? shadowolfyt
[13:56:54 WARN]: handleDisconnection() called twice
[13:56:59 INFO]: UUID of player shadowolfyt is 0af03841-2894-434c-a4be-965b317244e8
[13:56:59 INFO]: shadowolfyt[/127.0.0.1:53178] logged in with entity id 6 at ([world]-1517.8388062406163, NaN, 688.3248676937741)
[13:57:00 INFO]: shadowolfyt lost connection: Invalid move player packet received
[13:57:00 INFO]: ? shadowolfyt
[13:57:00 WARN]: handleDisconnection() called twice
[13:57:03 INFO]: UUID of player shadowolfyt is 0af03841-2894-434c-a4be-965b317244e8
[13:57:03 INFO]: shadowolfyt[/127.0.0.1:53185] logged in with entity id 12 at ([world]-1517.8388062406163, NaN, 688.3248676937741)
[13:57:04 INFO]: shadowolfyt lost connection: Invalid move player packet received
[13:57:04 INFO]: ? shadowolfyt
[13:57:04 WARN]: handleDisconnection() called twice
[13:57:16 INFO]: UUID of player shadowolfyt is 0af03841-2894-434c-a4be-965b317244e8
[13:57:16 INFO]: shadowolfyt[/127.0.0.1:53192] logged in with entity id 24 at ([world]-1517.8388062406163, NaN, 688.3248676937741)
[13:57:17 INFO]: shadowolfyt lost connection: Invalid move player packet received
[13:57:17 INFO]: ? shadowolfyt
[13:57:17 WARN]: handleDisconnection() called twice
